// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:login_flutter/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaunJrZfmVkcX6XQidUh5fi6F7VntnZ8w',
    appId: '1:983016538635:web:90f5fbbe627245606abd0e',
    messagingSenderId: '983016538635',
    projectId: 'appmusi-4ff75',
    authDomain: 'appmusi-4ff75.firebaseapp.com',
    storageBucket: 'appmusi-4ff75.firebasestorage.app',
    measurementId: 'G-BVT58PW6HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjwVpgWQabsmUTvLJGsRopbKz0b_B2qKo',
    appId: '1:983016538635:android:5965e5788dcd5e2a6abd0e',
    messagingSenderId: '983016538635',
    projectId: 'appmusi-4ff75',
    storageBucket: 'appmusi-4ff75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBEm7KKg4r6Hp3bhL7dPH8por7Z5fi2Us',
    appId: '1:983016538635:ios:db97b2b5cb27c1ce6abd0e',
    messagingSenderId: '983016538635',
    projectId: 'appmusi-4ff75',
    storageBucket: 'appmusi-4ff75.firebasestorage.app',
    iosBundleId: 'com.example.loginFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBEm7KKg4r6Hp3bhL7dPH8por7Z5fi2Us',
    appId: '1:983016538635:ios:db97b2b5cb27c1ce6abd0e',
    messagingSenderId: '983016538635',
    projectId: 'appmusi-4ff75',
    storageBucket: 'appmusi-4ff75.firebasestorage.app',
    iosBundleId: 'com.example.loginFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaunJrZfmVkcX6XQidUh5fi6F7VntnZ8w',
    appId: '1:983016538635:web:181dee3cd0291aaa6abd0e',
    messagingSenderId: '983016538635',
    projectId: 'appmusi-4ff75',
    authDomain: 'appmusi-4ff75.firebaseapp.com',
    storageBucket: 'appmusi-4ff75.firebasestorage.app',
    measurementId: 'G-B4GZCMZ1TF',
  );
}
